# Generated by Django 5.1 on 2025-11-06 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('too_high', 'Price too high'), ('too_low', 'Price too low'), ('wrong_product', 'Wrong product'), ('wrong_store', 'Wrong store'), ('outdated', 'Outdated price'), ('duplicate', 'Duplicate submission'), ('other', 'Other reason')], help_text='Reason for reporting', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Additional details about the report')),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.ForeignKey(help_text='Price being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.productprice')),
                ('reported_by', models.ForeignKey(help_text='User who reported this price', on_delete=django.db.models.deletion.CASCADE, related_name='price_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Report',
                'verbose_name_plural': 'Price Reports',
                'db_table': 'price_reports',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['price', '-reported_at'], name='price_repor_price_i_581296_idx'), models.Index(fields=['reported_by', '-reported_at'], name='price_repor_reporte_571dc2_idx')],
                'unique_together': {('price', 'reported_by')},
            },
        ),
        migrations.CreateModel(
            name='PriceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(help_text='Price being verified', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='products.productprice')),
                ('user', models.ForeignKey(help_text='User who verified this price', on_delete=django.db.models.deletion.CASCADE, related_name='price_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Verification',
                'verbose_name_plural': 'Price Verifications',
                'db_table': 'price_verifications',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['price', '-verified_at'], name='price_verif_price_i_168b5d_idx'), models.Index(fields=['user', '-verified_at'], name='price_verif_user_id_2ebddd_idx')],
                'unique_together': {('price', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Barcode that was scanned', max_length=50)),
                ('scan_type', models.CharField(choices=[('camera', 'Camera'), ('manual', 'Manual Entry')], default='camera', help_text='How the barcode was scanned', max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(help_text='Product that was scanned', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='products.product')),
                ('user', models.ForeignKey(help_text='User who scanned the product', on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'db_table': 'scan_history',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user', '-scanned_at'], name='scan_histor_user_id_34330c_idx'), models.Index(fields=['product', '-scanned_at'], name='scan_histor_product_2c9424_idx')],
            },
        ),
    ]
