# Generated by Django 5.1 on 2025-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricereport_priceverification_scanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='verified_count',
        ),
        migrations.AddField(
            model_name='priceverification',
            name='vote_type',
            field=models.CharField(choices=[('positive', 'Positive (Price is accurate)'), ('negative', 'Negative (Price is not accurate)')], default='positive', help_text='Type of vote: positive (accurate) or negative (inaccurate)', max_length=10),
        ),
        migrations.AddField(
            model_name='productprice',
            name='negative_votes',
            field=models.IntegerField(default=0, help_text='Number of negative votes (price is not accurate)'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='positive_votes',
            field=models.IntegerField(default=0, help_text='Number of positive votes (price is accurate)'),
        ),
    ]
