# Generated by Django 5.1 on 2025-11-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_vote_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Store address or location', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='chain',
            field=models.CharField(blank=True, default='', help_text='Store chain name (e.g., Kaufland, Lidl)', max_length=100),
        ),
    ]
