# Generated by Django 5.1 on 2025-11-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_store_address_alter_store_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City where the store is located', max_length=100),
        ),
    ]
