# Generated by Django 5.1 on 2025-11-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shopping list name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created this list', on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping List',
                'verbose_name_plural': 'Shopping Lists',
                'db_table': 'shopping_lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='Custom item name (if not a product from database)', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity needed')),
                ('checked', models.BooleanField(default=False, help_text='Whether this item has been purchased/checked off')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='User who added this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_list_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product from database (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='products.product')),
                ('shopping_list', models.ForeignKey(help_text='Shopping list this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'verbose_name': 'Shopping List Item',
                'verbose_name_plural': 'Shopping List Items',
                'db_table': 'shopping_list_items',
                'ordering': ['checked', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', help_text="Member's permission level", max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(help_text='Shopping list', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shopping.shoppinglist')),
                ('user', models.ForeignKey(help_text='Member user', on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping List Member',
                'verbose_name_plural': 'Shopping List Members',
                'db_table': 'shopping_list_members',
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['owner', '-updated_at'], name='shopping_li_owner_i_9f1c40_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', 'checked'], name='shopping_li_shoppin_31b8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistitem',
            index=models.Index(fields=['shopping_list', '-created_at'], name='shopping_li_shoppin_7406a9_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistmember',
            index=models.Index(fields=['shopping_list', 'user'], name='shopping_li_shoppin_12b8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglistmember',
            index=models.Index(fields=['user'], name='shopping_li_user_id_d030da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistmember',
            unique_together={('shopping_list', 'user')},
        ),
    ]
