# Generated by Django 5.1 on 2025-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's email address (used for login)", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Username (auto-generated if not provided)', max_length=150, null=True, unique=True),
        ),
    ]
