# Generated by Django 5.1 on 2025-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], default='en', help_text="User's preferred language for the interface", max_length=5),
        ),
    ]
